name: "Kwiat Quantum Information Group"
description: "Our group website"

url: "http://kdsec.org/group-website-jekyll/"
baseurl: "/group-website-jekyll/"
#baseurl: ""
paper-path: "papers/My Collection.Data/PDF"

markdown: kramdown
permalink: pretty
highlighter: null
excerpt_separator: <!--more-->
encoding: utf-8

gems:
  - jekyll-sitemap
